// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTestState(arg1, arg2) {
  return window['go']['main']['App']['ClearTestState'](arg1, arg2);
}

export function FetchLogsPage(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['FetchLogsPage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GenerateToken() {
  return window['go']['main']['App']['GenerateToken']();
}

export function GetDefaultOutputDir() {
  return window['go']['main']['App']['GetDefaultOutputDir']();
}

export function MQTTClientConnect(arg1) {
  return window['go']['main']['App']['MQTTClientConnect'](arg1);
}

export function MQTTClientDisconnect() {
  return window['go']['main']['App']['MQTTClientDisconnect']();
}

export function MQTTClientGetState() {
  return window['go']['main']['App']['MQTTClientGetState']();
}

export function MQTTClientPublish(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MQTTClientPublish'](arg1, arg2, arg3, arg4);
}

export function MQTTClientSubscribe(arg1, arg2) {
  return window['go']['main']['App']['MQTTClientSubscribe'](arg1, arg2);
}

export function MQTTClientUnsubscribe(arg1) {
  return window['go']['main']['App']['MQTTClientUnsubscribe'](arg1);
}

export function MQTTPickFile(arg1) {
  return window['go']['main']['App']['MQTTPickFile'](arg1);
}

export function PauseSimulation() {
  return window['go']['main']['App']['PauseSimulation']();
}

export function ResumeSimulation() {
  return window['go']['main']['App']['ResumeSimulation']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function StartSimulation(arg1) {
  return window['go']['main']['App']['StartSimulation'](arg1);
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}

export function TestMQTT(arg1) {
  return window['go']['main']['App']['TestMQTT'](arg1);
}

export function UpdateMQTTPubIntervals(arg1, arg2) {
  return window['go']['main']['App']['UpdateMQTTPubIntervals'](arg1, arg2);
}
