// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apiclient} from '../models';
import {mongoclient} from '../models';
import {main} from '../models';
import {simulator} from '../models';
import {utilities} from '../models';

export function ACClearHistory(arg1:string):Promise<void>;

export function ACDeleteCollection(arg1:string):Promise<void>;

export function ACDeleteEnvironment(arg1:string):Promise<void>;

export function ACDeleteRequest(arg1:string):Promise<void>;

export function ACDeleteWorkspace(arg1:string):Promise<void>;

export function ACExportCollection(arg1:string):Promise<string>;

export function ACImportCollection(arg1:string,arg2:string):Promise<void>;

export function ACListCollections(arg1:string):Promise<Array<apiclient.Collection>>;

export function ACListEnvVariables(arg1:string):Promise<Array<apiclient.EnvVariable>>;

export function ACListEnvironments(arg1:string):Promise<Array<apiclient.Environment>>;

export function ACListHistory(arg1:string):Promise<Array<apiclient.HistoryEntry>>;

export function ACListRequests(arg1:string):Promise<Array<apiclient.SavedRequest>>;

export function ACListWorkspaces():Promise<Array<apiclient.Workspace>>;

export function ACPickFile():Promise<{[key: string]: any}>;

export function ACSaveCollection(arg1:apiclient.Collection):Promise<apiclient.Collection>;

export function ACSaveEnvVariables(arg1:string,arg2:Array<apiclient.EnvVariable>):Promise<void>;

export function ACSaveEnvironment(arg1:apiclient.Environment):Promise<apiclient.Environment>;

export function ACSaveHistory(arg1:apiclient.HistoryEntry):Promise<void>;

export function ACSaveRequest(arg1:apiclient.SavedRequest):Promise<apiclient.SavedRequest>;

export function ACSaveWorkspace(arg1:apiclient.Workspace):Promise<apiclient.Workspace>;

export function ACSetActiveEnvironment(arg1:string,arg2:string):Promise<void>;

export function APIClientInit(arg1:string):Promise<void>;

export function APIClientSendRequest(arg1:apiclient.SendPayload):Promise<apiclient.SendResponse>;

export function ClearTestState(arg1:string,arg2:string):Promise<void>;

export function ExportFetchedData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function FetchLogsPage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<{[key: string]: any}>;

export function GenerateToken():Promise<string>;

export function GetDefaultOutputDir():Promise<string>;

export function GetResumeState(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function GetRunLogs(arg1:string,arg2:string,arg3:number,arg4:number):Promise<{[key: string]: any}>;

export function GetSystemMetrics():Promise<{[key: string]: any}>;

export function LogsFetchStart(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<void>;

export function LogsFetchStop():Promise<void>;

export function LogsGetMeta():Promise<{[key: string]: any}>;

export function LogsGetPage(arg1:number,arg2:number):Promise<{[key: string]: any}>;

export function LookupVehicleId(arg1:string,arg2:string,arg3:string):Promise<string>;

export function MCAggregate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<mongoclient.FindResult>;

export function MCClearQueryHistory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MCCollectionStats(arg1:string,arg2:string,arg3:string):Promise<mongoclient.CollStats>;

export function MCConnect(arg1:string):Promise<void>;

export function MCCreateCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MCCreateIndex(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function MCDeleteConnection(arg1:string):Promise<void>;

export function MCDeleteMany(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function MCDeleteOne(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function MCDisconnect(arg1:string):Promise<void>;

export function MCDropCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MCDropIndex(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MCExport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function MCFind(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<mongoclient.FindResult>;

export function MCImport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<mongoclient.ImportResult>;

export function MCInit(arg1:string):Promise<void>;

export function MCInsertOne(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function MCListCollections(arg1:string,arg2:string):Promise<Array<mongoclient.CollectionMeta>>;

export function MCListDatabases(arg1:string):Promise<Array<string>>;

export function MCListIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<mongoclient.Index>>;

export function MCListSavedConnections():Promise<Array<mongoclient.Connection>>;

export function MCPickFile():Promise<string>;

export function MCQueryHistory(arg1:string,arg2:string,arg3:string):Promise<Array<mongoclient.QueryEntry>>;

export function MCRenameCollection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MCRunRaw(arg1:string,arg2:string,arg3:string):Promise<mongoclient.RawResult>;

export function MCSaveConnection(arg1:string,arg2:string):Promise<mongoclient.Connection>;

export function MCSaveQueryHistory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function MCSchemaAnalyze(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<mongoclient.FieldStat>>;

export function MCTestConnection(arg1:string):Promise<void>;

export function MCUpdateConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MCUpdateOne(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function MQTTClientConnect(arg1:main.MQTTClientOpts):Promise<void>;

export function MQTTClientDisconnect():Promise<void>;

export function MQTTClientGetState():Promise<main.MQTTClientState>;

export function MQTTClientPublish(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function MQTTClientSubscribe(arg1:string,arg2:number):Promise<void>;

export function MQTTClientUnsubscribe(arg1:string):Promise<void>;

export function MQTTPickFile(arg1:string):Promise<string>;

export function PauseSimulation():Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function ResumeSimulation():Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveRunLogs(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchDevices(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectOutputDir():Promise<string>;

export function StartSimulation(arg1:simulator.Config):Promise<void>;

export function StopSimulation():Promise<void>;

export function SwitchAPIGet(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SwitchAPIPost(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function TestMQTT(arg1:simulator.RegionConfig):Promise<{[key: string]: any}>;

export function UpdateMQTTPubIntervals(arg1:number,arg2:number):Promise<void>;

export function UpdateNormalModeInterval(arg1:number):Promise<void>;

export function UpdateNormalModeIntervals(arg1:number,arg2:number):Promise<void>;

export function UtilCertToFormats(arg1:string):Promise<utilities.CertFormats>;

export function UtilCompress(arg1:string,arg2:string):Promise<utilities.CompressInfo>;

export function UtilDecompress(arg1:string,arg2:string):Promise<string>;

export function UtilHMAC(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UtilHash(arg1:string):Promise<{[key: string]: string}>;

export function UtilJSONToYAML(arg1:string):Promise<string>;

export function UtilOpenTextFile(arg1:string):Promise<string>;

export function UtilParseCert(arg1:string):Promise<utilities.CertInfo>;

export function UtilYAMLToJSON(arg1:string):Promise<string>;

export function ValidateSimulation(arg1:simulator.ValidateConfig):Promise<string>;
