// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {simulator} from '../models';

export function ClearTestState(arg1:string,arg2:string):Promise<void>;

export function FetchLogsPage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<{[key: string]: any}>;

export function GenerateToken():Promise<string>;

export function GetDefaultOutputDir():Promise<string>;

export function MQTTClientConnect(arg1:main.MQTTClientOpts):Promise<void>;

export function MQTTClientDisconnect():Promise<void>;

export function MQTTClientGetState():Promise<main.MQTTClientState>;

export function MQTTClientPublish(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function MQTTClientSubscribe(arg1:string,arg2:number):Promise<void>;

export function MQTTClientUnsubscribe(arg1:string):Promise<void>;

export function MQTTPickFile(arg1:string):Promise<string>;

export function PauseSimulation():Promise<void>;

export function ResumeSimulation():Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SelectOutputDir():Promise<string>;

export function StartSimulation(arg1:simulator.Config):Promise<void>;

export function StopSimulation():Promise<void>;

export function TestMQTT(arg1:simulator.RegionConfig):Promise<{[key: string]: any}>;

export function UpdateMQTTPubIntervals(arg1:number,arg2:number):Promise<void>;
