// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ACClearHistory(arg1) {
  return window['go']['main']['App']['ACClearHistory'](arg1);
}

export function ACDeleteCollection(arg1) {
  return window['go']['main']['App']['ACDeleteCollection'](arg1);
}

export function ACDeleteEnvironment(arg1) {
  return window['go']['main']['App']['ACDeleteEnvironment'](arg1);
}

export function ACDeleteRequest(arg1) {
  return window['go']['main']['App']['ACDeleteRequest'](arg1);
}

export function ACDeleteWorkspace(arg1) {
  return window['go']['main']['App']['ACDeleteWorkspace'](arg1);
}

export function ACExportCollection(arg1) {
  return window['go']['main']['App']['ACExportCollection'](arg1);
}

export function ACImportCollection(arg1, arg2) {
  return window['go']['main']['App']['ACImportCollection'](arg1, arg2);
}

export function ACListCollections(arg1) {
  return window['go']['main']['App']['ACListCollections'](arg1);
}

export function ACListEnvVariables(arg1) {
  return window['go']['main']['App']['ACListEnvVariables'](arg1);
}

export function ACListEnvironments(arg1) {
  return window['go']['main']['App']['ACListEnvironments'](arg1);
}

export function ACListHistory(arg1) {
  return window['go']['main']['App']['ACListHistory'](arg1);
}

export function ACListRequests(arg1) {
  return window['go']['main']['App']['ACListRequests'](arg1);
}

export function ACListWorkspaces() {
  return window['go']['main']['App']['ACListWorkspaces']();
}

export function ACPickFile() {
  return window['go']['main']['App']['ACPickFile']();
}

export function ACSaveCollection(arg1) {
  return window['go']['main']['App']['ACSaveCollection'](arg1);
}

export function ACSaveEnvVariables(arg1, arg2) {
  return window['go']['main']['App']['ACSaveEnvVariables'](arg1, arg2);
}

export function ACSaveEnvironment(arg1) {
  return window['go']['main']['App']['ACSaveEnvironment'](arg1);
}

export function ACSaveHistory(arg1) {
  return window['go']['main']['App']['ACSaveHistory'](arg1);
}

export function ACSaveRequest(arg1) {
  return window['go']['main']['App']['ACSaveRequest'](arg1);
}

export function ACSaveWorkspace(arg1) {
  return window['go']['main']['App']['ACSaveWorkspace'](arg1);
}

export function ACSetActiveEnvironment(arg1, arg2) {
  return window['go']['main']['App']['ACSetActiveEnvironment'](arg1, arg2);
}

export function APIClientInit(arg1) {
  return window['go']['main']['App']['APIClientInit'](arg1);
}

export function APIClientSendRequest(arg1) {
  return window['go']['main']['App']['APIClientSendRequest'](arg1);
}

export function ClearTestState(arg1, arg2) {
  return window['go']['main']['App']['ClearTestState'](arg1, arg2);
}

export function ExportFetchedData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportFetchedData'](arg1, arg2, arg3, arg4);
}

export function FetchLogsPage(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['FetchLogsPage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GenerateToken() {
  return window['go']['main']['App']['GenerateToken']();
}

export function GetDefaultOutputDir() {
  return window['go']['main']['App']['GetDefaultOutputDir']();
}

export function GetResumeState(arg1, arg2) {
  return window['go']['main']['App']['GetResumeState'](arg1, arg2);
}

export function GetRunLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRunLogs'](arg1, arg2, arg3, arg4);
}

export function GetSystemMetrics() {
  return window['go']['main']['App']['GetSystemMetrics']();
}

export function LogsFetchStart(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['LogsFetchStart'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function LogsFetchStop() {
  return window['go']['main']['App']['LogsFetchStop']();
}

export function LogsGetMeta() {
  return window['go']['main']['App']['LogsGetMeta']();
}

export function LogsGetPage(arg1, arg2) {
  return window['go']['main']['App']['LogsGetPage'](arg1, arg2);
}

export function LookupVehicleId(arg1, arg2, arg3) {
  return window['go']['main']['App']['LookupVehicleId'](arg1, arg2, arg3);
}

export function MCAggregate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MCAggregate'](arg1, arg2, arg3, arg4, arg5);
}

export function MCClearQueryHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['MCClearQueryHistory'](arg1, arg2, arg3);
}

export function MCCollectionStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['MCCollectionStats'](arg1, arg2, arg3);
}

export function MCConnect(arg1) {
  return window['go']['main']['App']['MCConnect'](arg1);
}

export function MCCreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['MCCreateCollection'](arg1, arg2, arg3);
}

export function MCCreateIndex(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MCCreateIndex'](arg1, arg2, arg3, arg4, arg5);
}

export function MCDeleteConnection(arg1) {
  return window['go']['main']['App']['MCDeleteConnection'](arg1);
}

export function MCDeleteMany(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MCDeleteMany'](arg1, arg2, arg3, arg4);
}

export function MCDeleteOne(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MCDeleteOne'](arg1, arg2, arg3, arg4);
}

export function MCDisconnect(arg1) {
  return window['go']['main']['App']['MCDisconnect'](arg1);
}

export function MCDropCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['MCDropCollection'](arg1, arg2, arg3);
}

export function MCDropIndex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MCDropIndex'](arg1, arg2, arg3, arg4);
}

export function MCExport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MCExport'](arg1, arg2, arg3, arg4, arg5);
}

export function MCFind(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['MCFind'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function MCImport(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['MCImport'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function MCInit(arg1) {
  return window['go']['main']['App']['MCInit'](arg1);
}

export function MCInsertOne(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MCInsertOne'](arg1, arg2, arg3, arg4);
}

export function MCListCollections(arg1, arg2) {
  return window['go']['main']['App']['MCListCollections'](arg1, arg2);
}

export function MCListDatabases(arg1) {
  return window['go']['main']['App']['MCListDatabases'](arg1);
}

export function MCListIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['MCListIndexes'](arg1, arg2, arg3);
}

export function MCListSavedConnections() {
  return window['go']['main']['App']['MCListSavedConnections']();
}

export function MCPickFile() {
  return window['go']['main']['App']['MCPickFile']();
}

export function MCQueryHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['MCQueryHistory'](arg1, arg2, arg3);
}

export function MCRenameCollection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MCRenameCollection'](arg1, arg2, arg3, arg4);
}

export function MCRunRaw(arg1, arg2, arg3) {
  return window['go']['main']['App']['MCRunRaw'](arg1, arg2, arg3);
}

export function MCSaveConnection(arg1, arg2) {
  return window['go']['main']['App']['MCSaveConnection'](arg1, arg2);
}

export function MCSaveQueryHistory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['MCSaveQueryHistory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function MCSchemaAnalyze(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MCSchemaAnalyze'](arg1, arg2, arg3, arg4, arg5);
}

export function MCTestConnection(arg1) {
  return window['go']['main']['App']['MCTestConnection'](arg1);
}

export function MCUpdateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['MCUpdateConnection'](arg1, arg2, arg3);
}

export function MCUpdateOne(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MCUpdateOne'](arg1, arg2, arg3, arg4, arg5);
}

export function MQTTClientConnect(arg1) {
  return window['go']['main']['App']['MQTTClientConnect'](arg1);
}

export function MQTTClientDisconnect() {
  return window['go']['main']['App']['MQTTClientDisconnect']();
}

export function MQTTClientGetState() {
  return window['go']['main']['App']['MQTTClientGetState']();
}

export function MQTTClientPublish(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MQTTClientPublish'](arg1, arg2, arg3, arg4);
}

export function MQTTClientSubscribe(arg1, arg2) {
  return window['go']['main']['App']['MQTTClientSubscribe'](arg1, arg2);
}

export function MQTTClientUnsubscribe(arg1) {
  return window['go']['main']['App']['MQTTClientUnsubscribe'](arg1);
}

export function MQTTPickFile(arg1) {
  return window['go']['main']['App']['MQTTPickFile'](arg1);
}

export function PauseSimulation() {
  return window['go']['main']['App']['PauseSimulation']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function ResumeSimulation() {
  return window['go']['main']['App']['ResumeSimulation']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveRunLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRunLogs'](arg1, arg2, arg3);
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function StartSimulation(arg1) {
  return window['go']['main']['App']['StartSimulation'](arg1);
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}

export function TestMQTT(arg1) {
  return window['go']['main']['App']['TestMQTT'](arg1);
}

export function UpdateMQTTPubIntervals(arg1, arg2) {
  return window['go']['main']['App']['UpdateMQTTPubIntervals'](arg1, arg2);
}

export function UpdateNormalModeInterval(arg1) {
  return window['go']['main']['App']['UpdateNormalModeInterval'](arg1);
}

export function UpdateNormalModeIntervals(arg1, arg2) {
  return window['go']['main']['App']['UpdateNormalModeIntervals'](arg1, arg2);
}

export function UtilCertToFormats(arg1) {
  return window['go']['main']['App']['UtilCertToFormats'](arg1);
}

export function UtilCompress(arg1, arg2) {
  return window['go']['main']['App']['UtilCompress'](arg1, arg2);
}

export function UtilDecompress(arg1, arg2) {
  return window['go']['main']['App']['UtilDecompress'](arg1, arg2);
}

export function UtilHMAC(arg1, arg2, arg3) {
  return window['go']['main']['App']['UtilHMAC'](arg1, arg2, arg3);
}

export function UtilHash(arg1) {
  return window['go']['main']['App']['UtilHash'](arg1);
}

export function UtilJSONToYAML(arg1) {
  return window['go']['main']['App']['UtilJSONToYAML'](arg1);
}

export function UtilOpenTextFile(arg1) {
  return window['go']['main']['App']['UtilOpenTextFile'](arg1);
}

export function UtilParseCert(arg1) {
  return window['go']['main']['App']['UtilParseCert'](arg1);
}

export function UtilYAMLToJSON(arg1) {
  return window['go']['main']['App']['UtilYAMLToJSON'](arg1);
}

export function ValidateSimulation(arg1) {
  return window['go']['main']['App']['ValidateSimulation'](arg1);
}
